# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='score',
            new_name='result',
        ),
    ]
